authentication/urls.py
from django.urls import path
from authentication.views import signin, signout, signup

app_name = 'authentication'

urlpatterns = [
    path('signin/', signin, name='signin'),
    path('signout/', signout, name='signout'),
    path('signup/', signup, name='signup')
]

blogs/urls.py
from django.urls import path
from blogs.views import BlogDetailView, create_comment

app_name = 'blogs'

urlpatterns = [
    path('posts/<int:pk>/', BlogDetailView.as_view(), name="details"),
    path('posts/<int:post_pk>/comment/', create_comment, name="create_comment")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('products/', include('products.urls', namespace='products')),
    path('authentication/', include('authentication.urls', namespace='authentication')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('orders/', include('orders.urls', namespace='orders'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pages/urls.py
# urls
from django.urls import path

# views
from pages.views import (
    CartListView, HomePageView, ShopPageView, AboutPageView,
    BlogPageView, ContactsPageView)

app_name = 'pages'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('shop/', ShopPageView.as_view(), name='shop'),
    path('about/', AboutPageView.as_view(), name='about'),
    path('blog/', BlogPageView.as_view(), name='blog'),
    path('contact/', ContactsPageView.as_view(), name='contact'),
    path('cart/', CartListView.as_view(), name='cart')
]

products/urls.py
from django.urls import path

from products.views import ShopDetailView, WishlistPageView, add_to_wishlist, add_to_cart, add_cart_data

app_name = 'products'

urlpatterns = [
    path('<int:pk>/details/', ShopDetailView.as_view(), name="details"),
    path('wishlist/', WishlistPageView.as_view(), name='wishlist'),
    path('<int:product_pk>/add_to_wishlist/', add_to_wishlist, name='add_to_wishlist'),
    path('<int:pk>/add_to_cart/', add_to_cart, name='add_to_cart'),
    path('<int:pk>/quantity/<int:quantity>/', add_cart_data, name='add_cart_data')
]

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Male_Fashion Template">
    <meta name="keywords" content="Male_Fashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Male-Fashion | Template</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&display=swap"
    rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    {% block extra_css %}

    {% endblock %}
</head>

<body>
    {% include 'layouts/navbar.html' %}
    {% include 'layouts/header.html' %}
    {% block content %}

    {% endblock %}
    {% include 'layouts/footer.html' %}

    <!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery.nicescroll.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    {% block extra_js %}

    {% endblock %}
</body>

</html>

templates/layouts/footer.html
{% load static %}
<!-- Footer Section Begin -->
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="footer__about">
                    <div class="footer__logo">
                        <a href="#"><img src="{% static 'img/footer-logo.png' %}" alt=""></a>
                    </div>
                    <p>The customer is at the heart of our unique business model, which includes design.</p>
                    <a href="#"><img src="{% static 'img/payment.png' %}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-2 offset-lg-1 col-md-3 col-sm-6">
                <div class="footer__widget">
                    <h6>Shopping</h6>
                    <ul>
                        <li><a href="#">Clothing Store</a></li>
                        <li><a href="#">Trending Shoes</a></li>
                        <li><a href="#">Accessories</a></li>
                        <li><a href="#">Sale</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-3 col-sm-6">
                <div class="footer__widget">
                    <h6>Shopping</h6>
                    <ul>
                        <li><a href="#">Contact Us</a></li>
                        <li><a href="#">Payment Methods</a></li>
                        <li><a href="#">Delivary</a></li>
                        <li><a href="#">Return & Exchanges</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 offset-lg-1 col-md-6 col-sm-6">
                <div class="footer__widget">
                    <h6>NewLetter</h6>
                    <div class="footer__newslatter">
                        <p>Be the first to know about new arrivals, look books, sales & promos!</p>
                        <form action="#">
                            <input type="text" placeholder="Your email">
                            <button type="submit"><span class="icon_mail_alt"></span></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="footer__copyright__text">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    <p>Copyright ©
                        <script>
                            document.write(new Date().getFullYear());
                        </script>2020
                        All rights reserved | This template is made with <i class="fa fa-heart-o"
                        aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    </p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Footer Section End -->

<!-- Search Begin -->
<div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch">+</div>
        <form class="search-model-form">
            <input type="text" id="search-input" placeholder="Search here.....">
        </form>
    </div>
</div>
<!-- Search End -->

templates/layouts/header.html
{% load my_tags %}
{% load static %}
<!-- Header Section Begin -->
<header class="header">
    <div class="header__top">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-7">
                    <div class="header__top__left">
                        <p>Free shipping, 30-day return or refund guarantee.</p>
                        {% if request.user.is_authenticated %}
                            <p>Hello, {{ request.user.username  }}</p>
                        {% else %}
                            <p>Hello, who are you ?</p>
                        {% endif %}
                    </div>
                </div>
                <div class="col-lg-6 col-md-5">
                    <div class="header__top__right">
                        <div class="header__top__links">
                            {% if request.user.is_authenticated %}
                                <a href="{% url 'authentication:signout' %}">Sign out</a>
                            {% else %}
                                <a href="{% url 'authentication:signin' %}">Sign in</a>
                            {% endif %}
                            <a href="#">FAQs</a>
                        </div>
                        <div class="header__top__hover">
                            <span>UZ <i class="arrow_carrot-down"></i></span>
                            <ul>
                                <li>UZ</li>
                                <li>RU</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3">
                <div class="header__logo">
                    <a href="{% url 'pages:home' %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <nav class="header__menu mobile-menu">
                    <ul>
                        <li class="{% if request.path == '/' %} active {% endif %}"><a href="{% url 'pages:home' %}">Home</a></li>
                        <li class="{% if request.path == '/shop/' %} active {% endif %}"><a href="{% url 'pages:shop' %}">Shop</a></li>
                        <li class="{% if request.path == '/about/' %} active {% endif %}"><a href="{% url 'pages:about' %}">About</a></li>
                        <li class="{% if request.path == '/blog/' %} active {% endif %}"><a href="{% url 'pages:blog' %}">Blog</a></li>
                        <li class="{% if request.path == '/contact/' %} active {% endif %}"><a href="{% url 'pages:contact' %}">Contacts</a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3 col-md-3">
                <div class="header__nav__option">
                    <a href="#" class="search-switch"><img src="{% static 'img/icon/search.png' %}" alt=""></a>
                    <a href="{% url 'products:wishlist' %}"><img src="{% static 'img/icon/heart.png' %}" alt=""></a>
                    {% get_cart_info request coupon as cart_info %}
                    <a href="{% url 'pages:cart' %}"><img src="{% static 'img/icon/cart.png' %}" alt=""> <span>{{ cart_info.0 }}</span></a>
                    <div class="price">${{ cart_info.1 }}</div>
                </div>
            </div>
        </div>
        <div class="canvas__open"><i class="fa fa-bars"></i></div>
    </div>
</header>
<!-- Header Section End -->

templates/layouts/navbar.html
    {% load static %}
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Offcanvas Menu Begin -->
    <div class="offcanvas-menu-overlay"></div>
    <div class="offcanvas-menu-wrapper">
        <div class="offcanvas__option">
            <div class="offcanvas__links">
                <a href="{% url 'authentication:signin' %}">Sign in</a>
                <a href="#">FAQs</a>
            </div>
            <div class="offcanvas__top__hover">
                <span>Usd <i class="arrow_carrot-down"></i></span>
                <ul>
                    <li>USD</li>
                    <li>EUR</li>
                    <li>USD</li>
                </ul>
            </div>
        </div>
        <div class="offcanvas__nav__option">
            <a href="#" class="search-switch"><img src="{% static 'img/icon/search.png' %}" alt=""></a>
            <a href="#"><img src="{% static 'img/icon/heart.png' %}" alt=""></a>
            <a href="#"><img src="{% static 'img/icon/cart.png' %}" alt=""> <span>0</span></a>
            <div class="price">$0.00</div>
        </div>
        <div id="mobile-menu-wrap"></div>
        <div class="offcanvas__text">
            <p>Free shipping, 30-day return or refund guarantee.</p>
        </div>
    </div>
    <!-- Offcanvas Menu End -->