blogs/urls.py
from django.urls import path
from blogs.views import BlogDetailView, create_comment

app_name = 'blogs'

urlpatterns = [
    path('posts/<int:pk>/', BlogDetailView.as_view(), name="details"),
    path('posts/<int:post_pk>/comment/', create_comment, name="create_comment")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('products/', include('products.urls', namespace='products')),
    path('authentication/', include('authentication.urls', namespace='authentication')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('orders/', include('orders.urls', namespace='orders'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/urls.py
from django.urls import path
from orders.views import proceed_order

app_name = "orders"

urlpatterns = [
    path('proceed_order/', proceed_order, name="proceed_order")
]

pages/urls.py
# urls
from django.urls import path

# views
from pages.views import (
    CartListView, HomePageView, ShopPageView, AboutPageView,
    BlogPageView, ContactsPageView)

app_name = 'pages'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('shop/', ShopPageView.as_view(), name='shop'),
    path('about/', AboutPageView.as_view(), name='about'),
    path('blog/', BlogPageView.as_view(), name='blog'),
    path('contact/', ContactsPageView.as_view(), name='contact'),
    path('cart/', CartListView.as_view(), name='cart')
]

products/urls.py
from django.urls import path

from products.views import ShopDetailView, WishlistPageView, add_to_wishlist, add_to_cart, add_cart_data

app_name = 'products'

urlpatterns = [
    path('<int:pk>/details/', ShopDetailView.as_view(), name="details"),
    path('wishlist/', WishlistPageView.as_view(), name='wishlist'),
    path('<int:product_pk>/add_to_wishlist/', add_to_wishlist, name='add_to_wishlist'),
    path('<int:pk>/add_to_cart/', add_to_cart, name='add_to_cart'),
    path('<int:pk>/quantity/<int:quantity>/', add_cart_data, name='add_cart_data')
]

blogs/models.py
from django.db import models

from products.models import TagModel

# Create your models here.

class AuthorModel(models.Model):
    full_name = models.CharField(max_length=64)
    avatar = models.ImageField(upload_to="posts/avatars")
    date_of_birth = models.DateField()

    def __str__(self):
        return self.full_name
    
    class Meta:
        verbose_name = "Author"
        verbose_name_plural = "Authors"


class PostModel(models.Model):
    title = models.CharField(max_length=64)
    description = models.TextField()
    short_description = models.CharField(max_length=124)
    image = models.ImageField(upload_to="posts/")
    author = models.ForeignKey(AuthorModel, on_delete=models.CASCADE)
    tags = models.ManyToManyField(TagModel)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    def get_previous(self):
        return self.get_previous_by_created_at()
    
    def get_next(self):
        return self.get_next_by_created_at()
    
    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Posts"


class CommentModel(models.Model):
    name = models.CharField(max_length=36)
    email = models.EmailField()
    phone = models.CharField(max_length=13)
    text = models.TextField()
    post = models.ForeignKey(PostModel, on_delete=models.CASCADE, related_name="comments")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"{self.name} | {self.post.title} | {self.text[:30]}"
    
    
    class Meta:
        verbose_name = "Comment"
        verbose_name_plural = "Comments"
    

blogs/views.py
from django.shortcuts import redirect
from django.views.generic import DetailView

from blogs.models import CommentModel, PostModel

# Create your views here.

# DetailView CBV
class BlogDetailView(DetailView):
    template_name = "blog-details.html"
    model = PostModel
    context_object_name = "post"


# Detail View FBV
# def blog_detail_view(request, pk):
#     post = PostModel.objects.get(pk=pk)
#     context = {
#         "post": post
#     }
#     return render(request, template_name="blog-details.html", context=context)


def create_comment(request, post_pk):
    post = PostModel.objects.get(pk=post_pk)
    if request.method == "POST":
        name = request.POST.get("name")
        email = request.POST.get("email")
        phone = request.POST.get("phone")
        text = request.POST.get("text")
        CommentModel.objects.create(
            name=name, email=email,
            phone=phone, text=text,
            post=post
        )
    return redirect('blogs:details', pk=post_pk)

templates/blog-details.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
    <!-- Blog Details Hero Begin -->
    <section class="blog-hero spad">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-9 text-center">
                    <div class="blog__hero__text">
                        <h2>{{ post.title }}</h2>
                        <ul>
                            <li>By {{ post.author.full_name }}</li>
                            <li>{{ post.created_at|date:'F d, Y' }}</li>
                            <li>{{ post.comments.all.count }} Comments</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Details Hero End -->

    <!-- Blog Details Section Begin -->
    <section class="blog-details spad">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-12">
                    <div class="blog__details__pic">
                        <img src="{{ post.image.url }}" alt="">
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="blog__details__content">
                        <div class="blog__details__share">
                            <span>share</span>
                            <ul>
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#" class="twitter"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#" class="youtube"><i class="fa fa-youtube-play"></i></a></li>
                                <li><a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                        <div class="blog__details__text">
                            <p>{{ post.description }}</p>
                            <p>{{ post.short_description }}</p>
                        </div>
                        <div class="blog__details__quote">
                            <i class="fa fa-quote-left"></i>
                            <p>“When designing an advertisement for a particular product many things should be
                                researched like where it should be displayed.”</p>
                            <h6>_ John Smith _</h6>
                        </div>
                        <div class="blog__details__option">
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="blog__details__author">
                                        <div class="blog__details__author__pic">
                                            <img src="{{  post.author.avatar.url}}" alt="">
                                        </div>
                                        <div class="blog__details__author__text">
                                            <h5>{{ post.author.full_name }}</h5>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="blog__details__tags">
                                        {% for tag in post.tags.all %}
                                            <a href="{% url 'pages:blog' %}?tag={{ tag.title }}">#{{ tag.title }}</a>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="blog__details__btns">
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    {% if post.get_previous %}
                                        <a href="{% url 'blogs:details' pk=post.get_previous.pk %}" class="blog__details__btns__item">
                                            <p><span class="arrow_left"></span> Previous Pod</p>
                                            <h5>{{ post.get_previous_by_created_at }}</h5>
                                        </a>
                                    {% endif %}
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    {% if post.get_next %}
                                        <a href="{% url 'blogs:details' pk=post.get_next.pk %}" class="blog__details__btns__item blog__details__btns__item--next">
                                            <p>Next Pod <span class="arrow_right"></span></p>
                                            <h5>{{ post.get_next_by_created_at }}</h5>
                                        </a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="comment__section">
                            <ul>
                                {% for comment in post.comments.all %}
                                <li class="media">
                                    <div class="media-body">
                                        <span class="text-muted pull-right">
                                            <small class="text-muted">
                                                {{ comment.created_at|timesince }}
                                            </small>
                                        </span>
                                        <strong>
                                            {{ comment.name }}
                                        </strong>
                                        <p>
                                            {{ comment.text }}
                                        </p>
                                    </div>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="blog__details__comment">
                            <h4>Leave A Comment</h4>
                            <form action="{% url 'blogs:create_comment' post_pk=post.pk %}" method="POST">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-lg-4 col-md-4">
                                        <input name="name" type="text" placeholder="Name">
                                    </div>
                                    <div class="col-lg-4 col-md-4">
                                        <input name="email" type="text" placeholder="Email">
                                    </div>
                                    <div class="col-lg-4 col-md-4">
                                        <input name="phone" type="text" placeholder="Phone">
                                    </div>
                                    <div class="col-lg-12 text-center">
                                        <textarea name="text" placeholder="Comment"></textarea>
                                        <button type="submit" class="site-btn">Post Comment</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Details Section End -->
{% endblock %}

templates/home.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}
     <!-- Hero Section Begin -->
 <section class="hero">
    <div class="hero__slider owl-carousel">
        {% for banner in object_list %}
        <div class="hero__items set-bg" data-setbg="{{ banner.image.url }}">
            <div class="container">
                <div class="row">
                    <div class="col-xl-5 col-lg-7 col-md-8">
                        <div class="hero__text">
                            <h6>{{ banner.collection }}</h6>
                            <h2>{{ banner.title }}</h2>
                            <p>{{ banner.description }}</p>
                            <a href="{% url 'pages:shop' %}" class="primary-btn">Shop now <span class="arrow_right"></span></a>
                            <div class="hero__social">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-pinterest"></i></a>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</section>
<!-- Hero Section End -->

<!-- Banner Section Begin -->
<section class="banner spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-7 offset-lg-4">
                <div class="banner__item">
                    <div class="banner__item__pic">
                        <img src="{% static 'img/banner/banner-1.jpg' %}" alt="">
                    </div>
                    <div class="banner__item__text">
                        <h2>Clothing Collections 2030</h2>
                        <a href="#">Shop now</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-5">
                <div class="banner__item banner__item--middle">
                    <div class="banner__item__pic">
                        <img src="{% static 'img/banner/banner-2.jpg' %}" alt="">
                    </div>
                    <div class="banner__item__text">
                        <h2>Accessories</h2>
                        <a href="#">Shop now</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-7">
                <div class="banner__item banner__item--last">
                    <div class="banner__item__pic">
                        <img src="{% static 'img/banner/banner-3.jpg' %}" alt="">
                    </div>
                    <div class="banner__item__text">
                        <h2>Shoes Spring 2030</h2>
                        <a href="#">Shop now</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Banner Section End -->

<!-- Product Section Begin -->
<section class="product spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <ul class="filter__controls">
                    <li></li>
                    <li class="active"><h2>Products</h2></li>
                    <li></li>
                </ul>
            </div>
        </div>
        <div class="row product__filter">
            {% for product in products %}
            <div class="col-lg-3 col-md-6 col-sm-6 col-md-6 col-sm-6 mix new-arrivals">
                <div class="product__item">
                    <div class="product__item__pic set-bg" data-setbg="{{ product.image.url }}">
                        <span class="label">New</span>
                        <ul class="product__hover">
                            <li>
                                <a href="{% url 'products:add_to_wishlist' product_pk=product.pk %}">
                                    {% if request.user.is_authenticated %}
                                        {% if request.user|in_wishlist:product %}
                                            <img src="{% static 'img/icon/heartr.png' %}" alt="">
                                        {% else %}
                                            <img src="{% static 'img/icon/heart.png' %}" alt="">
                                        {% endif %}
                                    {% else %}
                                        <img src="{% static 'img/icon/heart.png' %}" alt="">
                                    {% endif %}
                                </a>
                            </li>
                            <li><a href="{% url 'products:details' pk=product.pk %}"><img src="{% static 'img/icon/search.png' %}" alt=""></a></li>
                        </ul>
                    </div>
                    <div class="product__item__text">
                        <h6>{{ product.name }}</h6>
                        <a href="#" class="add-cart">+ Add To Cart</a>
                        <p><i class="fa fa-star-o"></i>{{ product.rating }}</p>
                        <div class="rating">
                            <i class="fa fa-star-o"></i>
                            <i class="fa fa-star-o"></i>
                            <i class="fa fa-star-o"></i>
                            <i class="fa fa-star-o"></i>
                            <i class="fa fa-star-o"></i>
                        </div>
                        <h5>${{ product.price }}</h5>
                        <div class="product__color__select">
                            <label for="pc-1">
                                <input type="radio" id="pc-1">
                            </label>
                            <label class="active black" for="pc-2">
                                <input type="radio" id="pc-2">
                            </label>
                            <label class="grey" for="pc-3">
                                <input type="radio" id="pc-3">
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<!-- Product Section End -->

<!-- Categories Section Begin -->
<section class="categories spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="categories__text">
                    <h2>Clothings Hot <br /> <span>Shoe Collection</span> <br /> Accessories</h2>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="categories__hot__deal">
                    <img src="{% static 'img/product-sale.png' %}" alt="">
                    <div class="hot__deal__sticker">
                        <span>Sale Of</span>
                        <h5>$29.99</h5>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 offset-lg-1">
                <div class="categories__deal__countdown">
                    <span>Deal Of The Week</span>
                    <h2>Multi-pocket Chest Bag Black</h2>
                    <div class="categories__deal__countdown__timer" id="countdown">
                        <div class="cd-item">
                            <span>3</span>
                            <p>Days</p>
                        </div>
                        <div class="cd-item">
                            <span>1</span>
                            <p>Hours</p>
                        </div>
                        <div class="cd-item">
                            <span>50</span>
                            <p>Minutes</p>
                        </div>
                        <div class="cd-item">
                            <span>18</span>
                            <p>Seconds</p>
                        </div>
                    </div>
                    <a href="#" class="primary-btn">Shop now</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Categories Section End -->

<!-- Instagram Section Begin -->
<section class="instagram spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="instagram__pic">
                    <div class="instagram__pic__item set-bg" data-setbg="{% static 'img/instagram/instagram-1.jpg' %}"></div>
                    <div class="instagram__pic__item set-bg" data-setbg="{% static 'img/instagram/instagram-2.jpg' %}"></div>
                    <div class="instagram__pic__item set-bg" data-setbg="{% static 'img/instagram/instagram-3.jpg' %}"></div>
                    <div class="instagram__pic__item set-bg" data-setbg="{% static 'img/instagram/instagram-4.jpg' %}"></div>
                    <div class="instagram__pic__item set-bg" data-setbg="{% static 'img/instagram/instagram-5.jpg' %}"></div>
                    <div class="instagram__pic__item set-bg" data-setbg="{% static 'img/instagram/instagram-6.jpg' %}"></div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="instagram__text">
                    <h2>Instagram</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                    labore et dolore magna aliqua.</p>
                    <h3>#Male_Fashion</h3>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Instagram Section End -->

<!-- Latest Blog Section Begin -->
<section class="latest spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title">
                    <span>Latest News</span>
                    <h2>Fashion New Trends</h2>
                </div>
            </div>
        </div>
        <div class="row">
            {% for post in posts %}
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="blog__item">
                        <div class="blog__item__pic set-bg" data-setbg="{{ post.image.url }}"></div>
                        <div class="blog__item__text">
                            <span><img src="{% static 'img/icon/calendar.png' %}" alt="">{{ post.created_at|date:'d F, Y' }}</span>
                            <h5>{{ post.title }}</h5>
                            <a href="{% url 'blogs:details' pk=post.pk %}">Read More</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>
<!-- Latest Blog Section End -->
{% endblock %}

templates/shopping-cart.html
{% extends 'layouts/base.html' %}

{% load my_tags %}
{% load static %}

{% block content %}
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__text">
                        <h4>Shopping Cart</h4>
                        <div class="breadcrumb__links">
                            <a href="./index.html">Home</a>
                            <a href="./shop.html">Shop</a>
                            <span>Shopping Cart</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Shopping Cart Section Begin -->
    <section class="shopping-cart spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="shopping__cart__table">
                        <div class="order__message">
                            {% if messages %}
                                <ul style="list-style: none;" class="messages alert alert-success" role="alert">
                                    {% for message in messages %}
                                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                        <table>
                            <thead>
                                <tr>
                                    <th>Product</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for product in products %}
                                    <form method="GET">
                                        {% csrf_token %}
                                        <tr>
                                            <td class="product__cart__item">
                                                <div class="product__cart__item__pic">
                                                    <img width="100" src="{{ product.image.url }}" alt="">
                                                </div>
                                                <div class="product__cart__item__text">
                                                    <h6>{{ product.name }}</h6>
                                                    <h5>${{ product.get_real_price }}<span class="ml-3 text-danger"><s>${{ product.price }}</s></span></h5>
                                                </div>
                                            </td>
                                            <td class="quantity__item">
                                                <div class="quantity">
                                                        <div class="pro-qty-2">
                                                            <input name="quantity" type="text" value="1" onclick="this.form.submit()">
                                                        </div>
                                                </div>
                                            </td>
                                            <td class="cart__price">$ 30.00</td>
                                            <td class="cart__close"><a href="{% url 'products:add_to_cart' pk=product.pk %}"><i class="fa fa-close"></i></a></td>
                                        </tr>
                                    </form>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                            {% if products %}
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="continue__btn">
                                        <a href="{% url 'pages:shop' %}">Continue Shopping</a>
                                    </div>
                                </div> 
                            {% endif %}
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="continue__btn update__btn">
                                    <a href=""><i class="fa fa-spinner"></i> Update cart</a>
                                </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="cart__discount">
                        <h6>Discount codes</h6>
                        <div style="height: 50px;">
                            {% if not request.GET.coupon %}

                            {% else %}
                                    {% if coupon %}
                                        <div class="alert alert-success" role="alert">
                                            {{ coupon.code }} Activated ! with discount %{{ coupon.discount }}
                                        </div>
                                    {% else %}
                                        <div class="alert alert-danger" role="alert">
                                            Coupon not found or expired !
                                        </div>
                                    {% endif %}
                            {% endif %}
                        </div>
                        <form method="GET">
                            <input name="coupon" type="text" placeholder="Coupon code">
                            <button type="submit">Apply</button>
                        </form>
                    </div>
                    <div class="cart__total">
                        <h6>Cart total</h6>
                        <ul>
                            {% for product in products %}
                                <li>{{ product.name|slice:'30' }} <span>$ {{ product.get_real_price }}</span></li>
                            {% endfor %}
                            {% get_cart_info request coupon as cart_info %}
                            <li>Total <span>$ {{ cart_info.1 }}</span></li>
                        </ul>
                        <a onclick="return confirm('Are you sure ?')"; href="{% url 'orders:proceed_order' %}?total_price={{ cart_info.1 }}&code={{ coupon.code }}" class="primary-btn">Proceed to checkout</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Shopping Cart Section End -->
{% endblock %}

{% block extra_js %}
    <script>
        setInterval(function(){ $(".alert").fadeOut(); }, 4000);
    </script>
{% endblock %}